FROM mariadb:latest

# Copy the custom configuration file and init script
COPY ./50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf
COPY ./init-slave.sh /docker-entrypoint-initdb.d/

# Set the root password for MariaDB
ENV MARIADB_ROOT_PASSWORD=0000
ENV MYSQL_ROOT_PASSWORD=0000

# Make sure the init script is executable
RUN chmod +x /docker-entrypoint-initdb.d/init-slave.sh
RUN chown -R mysql:mysql /etc/mysql/mariadb.conf.d
