groups:
  - name: instance_down
    rules:
      - alert: InstanceDown
        expr: up == 0  # 'up' is a metric that indicates whether a target is reachable (1 = up, 0 = down)
        for: 1m  # Wait for 1 minute before firing the alert
        labels:
          severity: critical  # Set the severity level
        annotations:
          summary: "Instance {{ $labels.instance }} is down"
          description: "The instance {{ $labels.instance }} (job: {{ $labels.job }}) has been down for more than 1 minute."

  - name: example
    rules:
      - alert: HighCpuUsage
        expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage on {{ $labels.instance }} is above 80% for the last 5 minutes."

      - alert: LowMemory
        expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100 < 20
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Low memory available"
          description: "Memory available on {{ $labels.instance }} is below 20% for the last 5 minutes."
